# Generated by Django 4.2.7 on 2023-11-10 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_total', models.PositiveIntegerField()),
                ('date_commande', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('prix_additionnel', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('nombre', models.IntegerField(null=True)),
                ('prix_unitaire', models.PositiveIntegerField()),
                ('image', models.ImageField(default='decoration/defaultImage.png', upload_to='decorations/')),
            ],
        ),
        migrations.CreateModel(
            name='DecorationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveSmallIntegerField(null=True)),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.decoration')),
            ],
        ),
        migrations.CreateModel(
            name='DecorationSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveSmallIntegerField(null=True)),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.decoration')),
            ],
        ),
        migrations.CreateModel(
            name='DetailCasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articlePanier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.articlepanier')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acteurClass', models.CharField(max_length=255)),
                ('acteurID', models.PositiveIntegerField()),
                ('cibleClass', models.CharField(blank=True, max_length=255)),
                ('cibleID', models.PositiveIntegerField(null=True)),
                ('action', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='package_images/')),
            ],
        ),
        migrations.CreateModel(
            name='LocationDeco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.decoration')),
            ],
        ),
        migrations.CreateModel(
            name='LocationSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_debutLoc', models.DateTimeField(null=True)),
                ('date_finLoc', models.DateTimeField(null=True)),
                ('decoree', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('prix', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProduitPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveSmallIntegerField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='store.package')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('prix', models.PositiveIntegerField()),
                ('image', models.ImageField(default='salles/defaultImage.png', upload_to='salles/')),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articlePanier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.articlepanier')),
            ],
        ),
        migrations.CreateModel(
            name='TypeDeco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('descritpion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.RemoveField(
            model_name='commande',
            name='client_guest',
        ),
        migrations.AddField(
            model_name='commande',
            name='date_debutLoc',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_finLoc',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='panier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.panier'),
        ),
        migrations.AddField(
            model_name='panier',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panier', to='store.client'),
        ),
        migrations.AddField(
            model_name='panier',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='particulier',
            name='cin_recto',
            field=models.ImageField(default='client/CIN-recto/defaultImage.png', upload_to='client/CIN-recto/'),
        ),
        migrations.AddField(
            model_name='particulier',
            name='cin_verso',
            field=models.ImageField(default='client/CIN-verso/defaultImage.png', upload_to='client/CIN-verso/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(default='products/defaultImage.png', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='categorie',
            field=models.CharField(choices=[('Société', 'Société'), ('Particulier', 'Particulier'), ('Guest', 'Guest')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_unitaire',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='CustomizedDecorationSalle',
            fields=[
                ('decorationsalle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.decorationsalle')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.client')),
                ('customization_options', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decoration_option', to='store.customizationoption')),
            ],
            bases=('store.decorationsalle',),
        ),
        migrations.CreateModel(
            name='CustomizedPackage',
            fields=[
                ('package_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.package')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.client')),
                ('customization_options', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_option', to='store.customizationoption')),
            ],
            bases=('store.package',),
        ),
        migrations.DeleteModel(
            name='ArticleCommande',
        ),
        migrations.AddField(
            model_name='sortie',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.commande'),
        ),
        migrations.AddField(
            model_name='sortie',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.produit'),
        ),
        migrations.AddField(
            model_name='produitpackage',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.produit'),
        ),
        migrations.AddField(
            model_name='package',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.salle'),
        ),
        migrations.AddField(
            model_name='locationsalle',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.client'),
        ),
        migrations.AddField(
            model_name='locationsalle',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.salle'),
        ),
        migrations.AddField(
            model_name='locationdeco',
            name='locationSalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.locationsalle'),
        ),
        migrations.AddField(
            model_name='imagepackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.package'),
        ),
        migrations.AddField(
            model_name='detailcasse',
            name='commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.commande'),
        ),
        migrations.AddField(
            model_name='detailcasse',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.produit'),
        ),
        migrations.AddField(
            model_name='decorationsalle',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorations', to='store.salle'),
        ),
        migrations.AddField(
            model_name='decorationpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorations', to='store.package'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.typedeco'),
        ),
        migrations.AddField(
            model_name='commandepackage',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.client'),
        ),
        migrations.AddField(
            model_name='commandepackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.package'),
        ),
    ]
