# Generated by Django 4.2.7 on 2023-11-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_commandepackage_customizationoption_decoration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='description',
        ),
    ]
