# Generated by Django 4.2.7 on 2023-11-12 12:48

from django.db import migrations, models
import django.db.models.deletion
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_commande_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HahitantsoaClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('contact', models.PositiveIntegerField(null=True)),
                ('categorie', models.CharField(choices=[('Société', 'Société'), ('Particulier', 'Particulier'), ('Guest', 'Guest')], max_length=50, null=True)),
                ('rdv', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HahitantsoaParticulier',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.client')),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('num_CIN', models.PositiveIntegerField()),
                ('cin_date_delivrance', models.DateField()),
                ('cin_recto', models.ImageField(default='client/CIN-recto/defaultImage.png', upload_to='client/CIN-recto/')),
                ('cin_verso', models.ImageField(default='client/CIN-verso/defaultImage.png', upload_to='client/CIN-verso/')),
                ('certificat_residence', models.CharField(max_length=255)),
                ('lieu_residence', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('store.client',),
        ),
        migrations.CreateModel(
            name='HahitantsoaRendezVous',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.client')),
                ('dateRdv', models.DateTimeField()),
            ],
            bases=('store.client',),
        ),
        migrations.CreateModel(
            name='HahitantsoaSociete',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.client')),
                ('nomSociete', models.CharField(max_length=255)),
                ('domiciliation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('nif', models.PositiveIntegerField()),
                ('stat', models.PositiveIntegerField()),
            ],
            bases=('store.client',),
        ),
        migrations.CreateModel(
            name='HahitantsoaParticulierImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/images', validators=[store.validators.validate_file_size])),
                ('particulier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.hahitantsoaparticulier')),
            ],
        ),
    ]
