# Generated by Django 4.2.7 on 2023-11-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_hahitantsoaclient_hahitantsoaparticulier_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HahitantsoaClient',
        ),
        migrations.RemoveField(
            model_name='hahitantsoaparticulierimage',
            name='particulier',
        ),
        migrations.RemoveField(
            model_name='hahitantsoarendezvous',
            name='client_ptr',
        ),
        migrations.RemoveField(
            model_name='hahitantsoasociete',
            name='client_ptr',
        ),
        migrations.DeleteModel(
            name='HahitantsoaParticulier',
        ),
        migrations.DeleteModel(
            name='HahitantsoaParticulierImage',
        ),
        migrations.DeleteModel(
            name='HahitantsoaRendezVous',
        ),
        migrations.DeleteModel(
            name='HahitantsoaSociete',
        ),
    ]
