# Generated by Django 4.2.7 on 2023-11-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_hahitantsoaclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='HahitantsoaSociete',
            fields=[
                ('hahitantsoaclient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.hahitantsoaclient')),
                ('nomSociete', models.CharField(max_length=255)),
                ('domiciliation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('nif', models.PositiveIntegerField()),
                ('stat', models.PositiveIntegerField()),
            ],
            bases=('store.hahitantsoaclient',),
        ),
    ]
