# Generated by Django 4.2.7 on 2023-11-12 15:29

from django.db import migrations, models
import django.db.models.deletion
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_hahitantsoasociete'),
    ]

    operations = [
        migrations.CreateModel(
            name='HahitantsoaParticulier',
            fields=[
                ('hahitantsoaclient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.hahitantsoaclient')),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('num_CIN', models.PositiveIntegerField()),
                ('cin_date_delivrance', models.DateField()),
                ('cin_recto', models.ImageField(default='client/CIN-recto/defaultImage.png', upload_to='client/CIN-recto/')),
                ('cin_verso', models.ImageField(default='client/CIN-verso/defaultImage.png', upload_to='client/CIN-verso/')),
                ('certificat_residence', models.CharField(max_length=255)),
                ('lieu_residence', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('store.hahitantsoaclient',),
        ),
        migrations.CreateModel(
            name='HahitantsoaParticulierImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/images', validators=[store.validators.validate_file_size])),
                ('hahitantsoaParticulier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.hahitantsoaparticulier')),
            ],
        ),
    ]
