# Generated by Django 4.2.7 on 2023-11-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='prenom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
