# Generated by Django 4.2.7 on 2023-11-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_employer_nom_remove_employer_prenom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
