# Generated by Django 4.2.7 on 2023-11-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_produit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='motif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
