# Generated by Django 4.2.7 on 2023-11-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rendezvous_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='motif',
            field=models.TextField(blank=True),
        ),
    ]
