# Generated by Django 4.2.7 on 2023-12-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_client_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecorationPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveSmallIntegerField()),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.decoration')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorations', to='store.panier')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SallePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salle', to='store.panier')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.salle')),
            ],
        ),
        migrations.RemoveField(
            model_name='hahitantsoaparticulier',
            name='hahitantsoaclient_ptr',
        ),
        migrations.RemoveField(
            model_name='hahitantsoaparticulierimage',
            name='hahitantsoaParticulier',
        ),
        migrations.RemoveField(
            model_name='hahitantsoasociete',
            name='hahitantsoaclient_ptr',
        ),
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['date_commande']},
        ),
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'ordering': ['dateRdv']},
        ),
        migrations.AddField(
            model_name='commande',
            name='LocationDecoration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='LocationProduit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='LocationSalle',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HahitantsoaClient',
        ),
        migrations.DeleteModel(
            name='HahitantsoaParticulier',
        ),
        migrations.DeleteModel(
            name='HahitantsoaParticulierImage',
        ),
        migrations.DeleteModel(
            name='HahitantsoaSociete',
        ),
        migrations.AddField(
            model_name='evenement',
            name='commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.commande'),
        ),
    ]
