# Generated by Django 4.2.7 on 2023-12-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_decorationpanier_evenement_sallepanier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decorationsalle',
            name='decoration',
        ),
        migrations.RemoveField(
            model_name='decorationsalle',
            name='salle',
        ),
        migrations.RemoveField(
            model_name='locationdeco',
            name='decoration',
        ),
        migrations.RemoveField(
            model_name='locationdeco',
            name='locationSalle',
        ),
        migrations.RemoveField(
            model_name='locationsalle',
            name='client',
        ),
        migrations.RemoveField(
            model_name='locationsalle',
            name='salle',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='LocationDecoration',
            new_name='locationDecoration',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='LocationProduit',
            new_name='locationProduit',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='LocationSalle',
            new_name='locationSalle',
        ),
        migrations.DeleteModel(
            name='CustomizedDecorationSalle',
        ),
        migrations.DeleteModel(
            name='DecorationSalle',
        ),
        migrations.DeleteModel(
            name='LocationDeco',
        ),
        migrations.DeleteModel(
            name='LocationSalle',
        ),
    ]
