# Generated by Django 4.2.7 on 2023-12-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_decorationsalle_decoration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='locationDecoration',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='locationProduit',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='locationSalle',
            field=models.BooleanField(),
        ),
    ]
