# Generated by Django 4.2.7 on 2023-12-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_commande_locationdecoration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='decorationsSetted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='produitsSetted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='salleSetted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
