# Generated by Django 4.2.7 on 2023-12-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_commande_decorationssetted_commande_produitssetted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['date_debutLoc']},
        ),
        migrations.AddField(
            model_name='evenement',
            name='date',
            field=models.DateField(default='2002-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evenement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='nbPersonne',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
