# Generated by Django 4.2.7 on 2023-12-06 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_commande_options_evenement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='commande',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.commande'),
        ),
    ]
