# Generated by Django 4.2.7 on 2023-12-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_evenement_commande'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenement',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
