# Generated by Django 4.2.7 on 2023-12-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_evenement_options_alter_evenement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant_total',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
