# Generated by Django 4.2.7 on 2023-12-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_commande_montant_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='montant_total',
        ),
    ]
