# Generated by Django 4.2.7 on 2023-12-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_commande_montant_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant_payee',
            field=models.IntegerField(default=0),
        ),
    ]
