# Generated by Django 4.2.7 on 2023-12-08 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_commande_montant_payee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayementPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payements', to='store.panier')),
            ],
        ),
        migrations.CreateModel(
            name='FraisSuppPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField()),
                ('motif', models.TextField()),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_additionnels', to='store.panier')),
            ],
        ),
    ]
