# Generated by Django 4.2.7 on 2023-12-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_payementpanier_fraissupppanier'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='reste',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='reste',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salle',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salle',
            name='etat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
