# Generated by Django 4.2.7 on 2023-12-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_decoration_reste_produit_reste_salle_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='retour_checked',
            field=models.BooleanField(default=False),
        ),
    ]
