# Generated by Django 4.2.7 on 2023-12-10 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_commande_retour_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailcasse',
            name='produit',
        ),
        migrations.CreateModel(
            name='CassePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveSmallIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.articlepanier')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casse', to='store.panier')),
            ],
        ),
    ]
