# Generated by Django 4.2.7 on 2023-12-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_remove_detailcasse_produit_cassepanier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cassepanier',
            old_name='quantite',
            new_name='quantiteCasse',
        ),
    ]
