# Generated by Django 4.2.7 on 2023-12-10 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_rename_quantite_cassepanier_quantitecasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasseArticlePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiteCasse', models.PositiveSmallIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.articlepanier')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casse_article', to='store.panier')),
            ],
        ),
        migrations.CreateModel(
            name='CasseDecorationPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiteCasse', models.PositiveSmallIntegerField(default=0)),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.decorationpanier')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casse_deco', to='store.panier')),
            ],
        ),
        migrations.DeleteModel(
            name='CassePanier',
        ),
    ]
