# Generated by Django 4.2.7 on 2023-12-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_client_date_ajout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_ajout',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
