# Generated by Django 4.2.7 on 2023-12-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_client_date_ajout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='nif',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='societe',
            name='stat',
            field=models.CharField(max_length=255),
        ),
    ]
