# Generated by Django 4.2.7 on 2023-12-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_societe_nif_alter_societe_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='payement_casse',
            field=models.BooleanField(default=False),
        ),
    ]
