# Generated by Django 4.2.7 on 2023-12-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_commande_payement_casse'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='organised',
            field=models.BooleanField(default=False),
        ),
    ]
