# Generated by Django 4.2.7 on 2023-12-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_commande_organised'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='commande_passee',
            field=models.BooleanField(default=False),
        ),
    ]
