# Generated by Django 4.2.7 on 2023-12-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_commande_commande_passee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='etat_paiement',
            field=models.CharField(choices=[('C', 'Complete'), ('A', 'Avance')], default='A', max_length=1),
        ),
    ]
