# Generated by Django 4.2.7 on 2023-12-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_commande_etat_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payementcassepanier',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='payementpanier',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
