# Generated by Django 4.2.7 on 2023-12-19 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_alter_payementcassepanier_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historique',
            name='date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='acteurClass',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='acteurID',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='cibleClass',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='cibleID',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='description',
        ),
        migrations.AddField(
            model_name='notification',
            name='evenement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.evenement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
