# Generated by Django 4.2.7 on 2023-12-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('A', 'Administrateur'), ('C', 'Responsable clientèle'), ('R', 'Responsable ressource'), ('A', 'Responsable finance')], default='C', max_length=1),
        ),
    ]
