# Generated by Django 4.2.7 on 2023-12-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(max_length=1),
        ),
    ]
