# Generated by Django 4.2.5 on 2023-09-20 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adresse',
            new_name='prenom',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='date_naissance',
            new_name='rdv',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cin',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
