# Generated by Django 4.2.5 on 2023-09-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_adresse_client_prenom_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='ClientGuest',
        ),
    ]
