# Generated by Django 4.2.5 on 2023-09-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_client_clientguest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientguest',
            old_name='rdv',
            new_name='daterdv',
        ),
    ]
