# Generated by Django 4.2.5 on 2023-09-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_rdv_clientguest_daterdv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientguest',
            old_name='daterdv',
            new_name='rdv',
        ),
    ]
