# Generated by Django 4.2.5 on 2023-09-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_daterdv_clientguest_rdv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientguest',
            name='rdv',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
