# Generated by Django 4.2.7 on 2023-11-10 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=255)),
                ('solde', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FluxCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(blank=True)),
                ('montant', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(choices=[('', 'Aucun'), ('E', 'Entrée'), ('S', 'Sortie')], default='', max_length=50)),
                ('crediteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='accounts.account')),
                ('debiteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='accounts.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.categorieaccount'),
        ),
    ]
